version: "3.8"
services:
  postgres:
    ports:
      - 5432:5432
    build:
      context: .
      dockerfile: Dockerfile-postgres
    image: postgres-insurance-budget
    container_name: postgres-insurance-budget
    restart: on-failure

  springboot:
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: Dockerfile-springboot
    image: insurance-budget
    container_name: insurance-budget
    depends_on:
      - postgres
    restart: on-failure
